// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvbzwxeupsjxorwzewhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Ynp3eGV1cHNqeG9yd3pld2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDkzOTksImV4cCI6MjA1ODQ4NTM5OX0.pGSr7uAba1_G1mcnek-10tgxS-tZ-1vPu_guzB3MYcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);